### ISSUE TITLE
eval.py问题

### ISSUE THREAD

**Issue by swqsyy** [wangyuxin87/VisionLAN#21]
感谢您的代码，运行“CUDA_VISIBLE_DEVICES=0 python eval.py”命令后，报出如下错误：
Traceback (most recent call last):
  File "eval.py", line 11, in <module>
    import cfgs.cfgs_eval as cfgs
  File "/workspace/VisionLAN-main/cfgs/cfgs_eval.py", line 5, in <module>
    from data.dataset_scene import *
  File "/workspace/VisionLAN-main/data/dataset_scene.py", line 16, in <module>
    from transforms import CVColorJitter, CVDeterioration, CVGeometry
ModuleNotFoundError: No module named 'transforms'
看起来似乎是环境的问题，但我的环境是严格按照requirements.txt配置的，这是怎么回事呢？热切盼望您的解答

**Comment by ashishpapanai** [comment]
Hey,
You can import the transforms module relatively, which will solve the issue. 
replace, `transforms` with `.transforms`.

**Comment by ashishpapanai** [comment]
From my understanding, this seems to be an issue of relative import. 
Could you please try to change `transforms` to `.transforms` in line 16 of "/workspace/VisionLAN-main/data/dataset_scene.py"? 

This fixed the issue when I was trying to eval the model locally, and it might also work for you.
